"""empty message

Revision ID: 48224e27a1ae
Revises: b63d71807671
Create Date: 2022-10-18 08:50:49.830588

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '48224e27a1ae'
down_revision = 'b63d71807671'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exam_subject', sa.Column('subject', sa.String(length=100), nullable=False))
    op.drop_column('exam_subject', 'exam_subject')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exam_subject', sa.Column('exam_subject', sa.VARCHAR(length=100), nullable=False))
    op.drop_column('exam_subject', 'subject')
    # ### end Alembic commands ###
