"""empty message

Revision ID: e1c05a5f032b
Revises: 48224e27a1ae
Create Date: 2022-10-23 06:26:30.943853

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e1c05a5f032b'
down_revision = '48224e27a1ae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('image_file', sa.String(length=20), nullable=False),
    sa.Column('password', sa.String(length=60), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('notice',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('date_posted', sa.DateTime(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('student_result',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_name', sa.String(length=100), nullable=False),
    sa.Column('student_roll', sa.String(length=100), nullable=False),
    sa.Column('student_class', sa.String(length=100), nullable=False),
    sa.Column('student_mark_details', sa.String(length=500), nullable=False),
    sa.Column('subject_total_marks', sa.String(length=100), nullable=False),
    sa.Column('total_achive_mark', sa.String(length=100), nullable=False),
    sa.Column('total_achive_grade', sa.String(length=100), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('exam_id', sa.Integer(), nullable=False),
    sa.Column('exam_subject_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['exam_id'], ['exam.id'], ),
    sa.ForeignKeyConstraint(['exam_subject_id'], ['exam_subject.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('student_result')
    op.drop_table('notice')
    op.drop_table('user')
    # ### end Alembic commands ###
